MOD_NAME := aio
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/aio_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/aio.o $(DIR)/arch/hi3516cv500/aio.data.o
else
    OBJS += $(DIR)/aio.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
