MOD_NAME := vpss
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/vpss_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/vpss.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
