
.PHONY: default clean

default:
	@echo -e "\e[0;32;1m--Compiling 'cipher'...\e[0;36;1m"
	@@echo -e "\e[0m"
	@cd ./src;make;cd ../;

clean:
	@cd ./sample;make clean;cd ../;
	@cd ./src;make clean;cd ../;
