/*
 * Init wrapper for hi3519v101_sys blob module.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/sysctl.h>

extern int _3519v101_hi3519v101_sys_init(void);
extern void _3519v101_hi3519v101_sys_exit(void);

#define DECLARE_BLOB_SYM(sym) extern char sym[]
#define DECLARE_BLOB_FUNC(sym) extern int sym(void)

extern int vi_vpss_online;
module_param(vi_vpss_online, int, S_IRUGO);
EXPORT_SYMBOL(vi_vpss_online);

extern int en_online_delayint;
module_param(en_online_delayint, int, S_IRUGO);
EXPORT_SYMBOL(en_online_delayint);

extern unsigned int mem_total;
module_param(mem_total, uint, S_IRUGO);
EXPORT_SYMBOL(mem_total);

extern char *sensor[4];
module_param_array(sensor, charp, NULL, S_IRUGO);

extern void *reg_crg_base_va;		EXPORT_SYMBOL(reg_crg_base_va);
extern void *reg_sys_base_va;		EXPORT_SYMBOL(reg_sys_base_va);
extern void *reg_ddr0_base_va;		EXPORT_SYMBOL(reg_ddr0_base_va);
extern void *reg_misc_base_va;		EXPORT_SYMBOL(reg_misc_base_va);

/* SYS module funcs */
DECLARE_BLOB_FUNC(SYS_ModInit);		EXPORT_SYMBOL(SYS_ModInit);
DECLARE_BLOB_FUNC(SYS_ModExit);		EXPORT_SYMBOL(SYS_ModExit);
DECLARE_BLOB_FUNC(SYS_Init);		EXPORT_SYMBOL(SYS_Init);
DECLARE_BLOB_FUNC(SYS_Exit);		EXPORT_SYMBOL(SYS_Exit);
DECLARE_BLOB_FUNC(SYS_DRV_Init);	EXPORT_SYMBOL(SYS_DRV_Init);
DECLARE_BLOB_FUNC(SYS_DRV_Exit);	EXPORT_SYMBOL(SYS_DRV_Exit);
DECLARE_BLOB_FUNC(SYS_Bind);		EXPORT_SYMBOL(SYS_Bind);
DECLARE_BLOB_FUNC(SYS_UnBind);		EXPORT_SYMBOL(SYS_UnBind);
DECLARE_BLOB_FUNC(SYS_GetBindbyDest);	EXPORT_SYMBOL(SYS_GetBindbyDest);
DECLARE_BLOB_FUNC(SYS_GetBindbySrc);	EXPORT_SYMBOL(SYS_GetBindbySrc);
DECLARE_BLOB_FUNC(SYS_GetTimeStamp);	EXPORT_SYMBOL(SYS_GetTimeStamp);
DECLARE_BLOB_FUNC(SYS_GetLocalCurPts);	EXPORT_SYMBOL(SYS_GetLocalCurPts);
DECLARE_BLOB_FUNC(SYS_GetLocalTime);	EXPORT_SYMBOL(SYS_GetLocalTime);
DECLARE_BLOB_FUNC(SYS_SyncTimeStamp);	EXPORT_SYMBOL(SYS_SyncTimeStamp);
DECLARE_BLOB_FUNC(SYS_GetScaleCoeff);	EXPORT_SYMBOL(SYS_GetScaleCoeff);
DECLARE_BLOB_FUNC(SYS_SetScaleCoeff);	EXPORT_SYMBOL(SYS_SetScaleCoeff);
DECLARE_BLOB_FUNC(SYS_GetMmzName);	EXPORT_SYMBOL(SYS_GetMmzName);
DECLARE_BLOB_FUNC(SYS_GetMemDdr);	EXPORT_SYMBOL(SYS_GetMemDdr);
DECLARE_BLOB_FUNC(SYS_GetMemIndex);	EXPORT_SYMBOL(SYS_GetMemIndex);
DECLARE_BLOB_FUNC(SYS_GetNowString);	EXPORT_SYMBOL(SYS_GetNowString);
DECLARE_BLOB_FUNC(SYS_GetFormatTime);	EXPORT_SYMBOL(SYS_GetFormatTime);
DECLARE_BLOB_FUNC(SYS_GetSchedClock);	EXPORT_SYMBOL(SYS_GetSchedClock);
DECLARE_BLOB_FUNC(SYS_CheckTime);	EXPORT_SYMBOL(SYS_CheckTime);

DECLARE_BLOB_FUNC(SYS_BIND_Init);		EXPORT_SYMBOL(SYS_BIND_Init);
DECLARE_BLOB_FUNC(SYS_BIND_Exit);		EXPORT_SYMBOL(SYS_BIND_Exit);
DECLARE_BLOB_FUNC(SYS_BIND_MOD_Init);		EXPORT_SYMBOL(SYS_BIND_MOD_Init);
DECLARE_BLOB_FUNC(SYS_BIND_MOD_Exit);		EXPORT_SYMBOL(SYS_BIND_MOD_Exit);
DECLARE_BLOB_FUNC(SYS_BIND_RegisterSender);	EXPORT_SYMBOL(SYS_BIND_RegisterSender);
DECLARE_BLOB_FUNC(SYS_BIND_UnRegisterSender);	EXPORT_SYMBOL(SYS_BIND_UnRegisterSender);
DECLARE_BLOB_FUNC(SYS_BIND_RegisterReceiver);	EXPORT_SYMBOL(SYS_BIND_RegisterReceiver);
DECLARE_BLOB_FUNC(SYS_BIND_UnRegisterReceiver);EXPORT_SYMBOL(SYS_BIND_UnRegisterReceiver);
DECLARE_BLOB_FUNC(SYS_BIND_SendData);		EXPORT_SYMBOL(SYS_BIND_SendData);
DECLARE_BLOB_FUNC(SYS_BIND_ResetData);		EXPORT_SYMBOL(SYS_BIND_ResetData);
DECLARE_BLOB_FUNC(SYS_BIND_ProcShow);		EXPORT_SYMBOL(SYS_BIND_ProcShow);

/* SYS HAL exports */
DECLARE_BLOB_FUNC(SYS_HAL_Init);		EXPORT_SYMBOL(SYS_HAL_Init);
DECLARE_BLOB_FUNC(SYS_HAL_Exit);		EXPORT_SYMBOL(SYS_HAL_Exit);
DECLARE_BLOB_FUNC(SYS_HAL_GetChipID);		EXPORT_SYMBOL(SYS_HAL_GetChipID);
DECLARE_BLOB_FUNC(SYS_HAL_GetCustomCode);	EXPORT_SYMBOL(SYS_HAL_GetCustomCode);
DECLARE_BLOB_FUNC(SYS_HAL_SetMediaFreq);	EXPORT_SYMBOL(SYS_HAL_SetMediaFreq);
DECLARE_BLOB_FUNC(SYS_HAL_MediaRest);		EXPORT_SYMBOL(SYS_HAL_MediaRest);
DECLARE_BLOB_FUNC(SYS_HAL_ViuBusClkEn);	EXPORT_SYMBOL(SYS_HAL_ViuBusClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_ViuBusResetSel);	EXPORT_SYMBOL(SYS_HAL_ViuBusResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_ViuDevClkEn);	EXPORT_SYMBOL(SYS_HAL_ViuDevClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_ViuDevResetSel);	EXPORT_SYMBOL(SYS_HAL_ViuDevResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_VpssClkEn);		EXPORT_SYMBOL(SYS_HAL_VpssClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VpssResetSel);	EXPORT_SYMBOL(SYS_HAL_VpssResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_VeduClkEn);		EXPORT_SYMBOL(SYS_HAL_VeduClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VeduResetSel);	EXPORT_SYMBOL(SYS_HAL_VeduResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_HevcClkEn);		EXPORT_SYMBOL(SYS_HAL_HevcClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_HevcResetSel);	EXPORT_SYMBOL(SYS_HAL_HevcResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_JpgeClkEn);		EXPORT_SYMBOL(SYS_HAL_JpgeClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_JpgeResetSel);	EXPORT_SYMBOL(SYS_HAL_JpgeResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_TdeClkEn);		EXPORT_SYMBOL(SYS_HAL_TdeClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_TdeResetSel);	EXPORT_SYMBOL(SYS_HAL_TdeResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_VgsClkEn);		EXPORT_SYMBOL(SYS_HAL_VgsClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VgsResetSel);	EXPORT_SYMBOL(SYS_HAL_VgsResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_IveClkEn);		EXPORT_SYMBOL(SYS_HAL_IveClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_IveResetSel);	EXPORT_SYMBOL(SYS_HAL_IveResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_AioClkEn);		EXPORT_SYMBOL(SYS_HAL_AioClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_AioResetSel);	EXPORT_SYMBOL(SYS_HAL_AioResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_CipherClkEn);	EXPORT_SYMBOL(SYS_HAL_CipherClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_CipherResetSel);	EXPORT_SYMBOL(SYS_HAL_CipherResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_VouBusClkEn);	EXPORT_SYMBOL(SYS_HAL_VouBusClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VouBusResetSel);	EXPORT_SYMBOL(SYS_HAL_VouBusResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_VouDevClkEn);	EXPORT_SYMBOL(SYS_HAL_VouDevClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VouCoreClkEn);	EXPORT_SYMBOL(SYS_HAL_VouCoreClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VouAPBClkEn);	EXPORT_SYMBOL(SYS_HAL_VouAPBClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VouCFGClkEn);	EXPORT_SYMBOL(SYS_HAL_VouCFGClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VouOutClkEn);	EXPORT_SYMBOL(SYS_HAL_VouOutClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VouOutClkSel);	EXPORT_SYMBOL(SYS_HAL_VouOutClkSel);
DECLARE_BLOB_FUNC(SYS_HAL_VouHdClkSel);	EXPORT_SYMBOL(SYS_HAL_VouHdClkSel);
DECLARE_BLOB_FUNC(SYS_HAL_VouLcdClkEn);	EXPORT_SYMBOL(SYS_HAL_VouLcdClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_VouHdOutPctrl);	EXPORT_SYMBOL(SYS_HAL_VouHdOutPctrl);
DECLARE_BLOB_FUNC(SYS_HAL_VdacPctrl);		EXPORT_SYMBOL(SYS_HAL_VdacPctrl);
DECLARE_BLOB_FUNC(SYS_HAL_VouVdacClkEn);	EXPORT_SYMBOL(SYS_HAL_VouVdacClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_FisheyeClkEn);	EXPORT_SYMBOL(SYS_HAL_FisheyeClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_FisheyeResetSel);	EXPORT_SYMBOL(SYS_HAL_FisheyeResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_PcieClkEn);		EXPORT_SYMBOL(SYS_HAL_PcieClkEn);
DECLARE_BLOB_FUNC(SYS_HAL_PcieResetSel);	EXPORT_SYMBOL(SYS_HAL_PcieResetSel);
DECLARE_BLOB_FUNC(SYS_HAL_GetEfuseAddr);	EXPORT_SYMBOL(SYS_HAL_GetEfuseAddr);

DECLARE_BLOB_FUNC(SYS_DRV_Conver_ScaleCoef);	EXPORT_SYMBOL(SYS_DRV_Conver_ScaleCoef);
DECLARE_BLOB_FUNC(SYS_DRV_GetChipId);		EXPORT_SYMBOL(SYS_DRV_GetChipId);
DECLARE_BLOB_FUNC(SYS_DRV_GetChipVersion);	EXPORT_SYMBOL(SYS_DRV_GetChipVersion);
DECLARE_BLOB_FUNC(SYS_DRV_GetCustomCode);	EXPORT_SYMBOL(SYS_DRV_GetCustomCode);
DECLARE_BLOB_FUNC(SYS_DRV_GetStride);		EXPORT_SYMBOL(SYS_DRV_GetStride);
DECLARE_BLOB_FUNC(SYS_DRV_SetMediaFreq);	EXPORT_SYMBOL(SYS_DRV_SetMediaFreq);
DECLARE_BLOB_FUNC(SYS_DRV_Restore);		EXPORT_SYMBOL(SYS_DRV_Restore);
DECLARE_BLOB_FUNC(SYS_DRV_DrvIoCtrl);		EXPORT_SYMBOL(SYS_DRV_DrvIoCtrl);

DECLARE_BLOB_SYM(stSysDrvOps);			EXPORT_SYMBOL(stSysDrvOps);
DECLARE_BLOB_SYM(g_stSysSpinLock);		EXPORT_SYMBOL(g_stSysSpinLock);
DECLARE_BLOB_SYM(g_u32FuncId);			EXPORT_SYMBOL(g_u32FuncId);
DECLARE_BLOB_SYM(g_u32SysChipAddr);		EXPORT_SYMBOL(g_u32SysChipAddr);
DECLARE_BLOB_SYM(g_u32SysEfuseAddr);		EXPORT_SYMBOL(g_u32SysEfuseAddr);

extern int sys_sensor_num;
EXPORT_SYMBOL(sys_sensor_num);

static int __init sys_mod_init(void) { return _3519v101_hi3519v101_sys_init(); }
static void __exit sys_mod_exit(void) { _3519v101_hi3519v101_sys_exit(); }
module_init(sys_mod_init);
module_exit(sys_mod_exit);
MODULE_LICENSE("GPL");
