MOD_NAME := vo
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/vo_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/vo.o $(DIR)/arch/hi3516cv500/vo.data.o
else
    OBJS += $(DIR)/vo.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
