MOD_NAME := isp
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := \
	$(DIR)/arch/$(CHIPSET)/hal/isp_drv.c \
	$(DIR)/init/linux/isp_init.c \
	$(DIR)/mkp/src/isp.c \
	$(DIR)/mkp/src/isp_drv_vreg.c \
	$(DIR)/mkp/src/isp_list.c \
	$(DIR)/mkp/src/isp_st.c

ccflags-y += -I$(src)/$(MOD_NAME)/include
ccflags-y += -I$(src)/$(MOD_NAME)/arch/include
ccflags-y += -I$(src)/$(MOD_NAME)/ext_inc
ccflags-y += -I$(src)/$(MOD_NAME)/mkp/include
ccflags-y += -I$(src)/$(MOD_NAME)/arch/$(CHIPSET)/include
ccflags-y += -I$(src)/../libraries/isp/arch/$(CHIPSET)/include
ccflags-y += -I$(src)/../libraries/isp/include

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
