MOD_NAME := isp
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

ifeq ($(CHIPARCH),hi3516cv500)
SRCS := \
	$(DIR)/arch/$(CHIPARCH)/hal/isp_drv.c \
	$(DIR)/arch/$(CHIPARCH)/isp_init.c \
	$(DIR)/arch/$(CHIPARCH)/mkp/src/isp.c \
	$(DIR)/arch/$(CHIPARCH)/mkp/src/isp_drv_vreg.c \
	$(DIR)/arch/$(CHIPARCH)/mkp/src/isp_list.c \
	$(DIR)/arch/$(CHIPARCH)/mkp/src/isp_st.c

ccflags-y += -I$(src)/$(MOD_NAME)/arch/$(CHIPARCH)/include
ccflags-y += -I$(src)/$(MOD_NAME)/arch/$(CHIPARCH)/mkp/include
else
ccflags-y += -I$(src)/$(MOD_NAME)/arch/$(CHIPARCH)/include
ccflags-y += -I$(src)/$(MOD_NAME)/mkp/include
SRCS := \
	$(DIR)/arch/$(CHIPARCH)/hal/isp_drv.c \
	$(DIR)/init/linux/isp_init.c \
	$(DIR)/mkp/src/isp.c \
	$(DIR)/mkp/src/isp_drv_vreg.c \
	$(DIR)/mkp/src/isp_list.c \
	$(DIR)/mkp/src/isp_st.c
endif

ccflags-y += -I$(src)/$(MOD_NAME)/include
ccflags-y += -I$(src)/$(MOD_NAME)/arch/include

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
