MOD_NAME := ive
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/ive_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/ive.o $(DIR)/arch/hi3516cv500/ive.data.o
else
    OBJS += $(DIR)/ive.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
