MOD_NAME := rgn
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/rgn_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/rgn.o $(DIR)/arch/hi3516cv500/rgn.data.o
else
    OBJS += $(DIR)/rgn.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
