MOD_NAME := rgn
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/rgn_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/$(CHIPARCH)/rgn$(KO_LOG_SUFFIX).o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
