# Create by y00271809,2015/05/20
#*************************************************************************

ifeq ($(PARAM_FILE), )
	PARAM_FILE:=../../../../Makefile.param
	include $(PARAM_FILE)
endif

#*************************************************************************
# compile linux or HuaweiLite
include $(PWD)/Make.$(OSTYPE)



