MOD_NAME := h265e
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/h265e_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/h265e.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
