MOD_NAME := h265e
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/h265e_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/h265e.o $(DIR)/arch/hi3516cv500/h265e.data.o
else
    OBJS += $(DIR)/h265e.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
