MOD_NAME := ai
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/ai_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/$(CHIPARCH)/ai$(KO_LOG_SUFFIX).o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
