MOD_NAME := ai
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/ai_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/ai.o $(DIR)/arch/hi3516cv500/ai.data.o
else
    OBJS += $(DIR)/ai.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
