MOD_NAME := venc
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/venc_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/venc.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
