MOD_NAME := vedu
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/vedu_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/vedu.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
