MOD_NAME := vedu
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/vedu_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/vedu.o $(DIR)/arch/hi3516cv500/vedu.data.o
else
    OBJS += $(DIR)/vedu.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
