MOD_NAME := adec
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/adec_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/$(CHIPARCH)/adec$(KO_LOG_SUFFIX).o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
