MOD_NAME := adec
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/adec_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/adec.o $(DIR)/arch/hi3516cv500/adec.data.o
else
    OBJS += $(DIR)/adec.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
