MOD_NAME := vgs
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/vgs_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/$(CHIPARCH)/vgs$(KO_LOG_SUFFIX).o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
