MOD_NAME := nnie
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/nnie_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/arch/hi3516cv500/nnie.o $(DIR)/arch/hi3516cv500/nnie.data.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
