MOD_NAME := dis
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/dis_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/arch/hi3516cv500/dis.o $(DIR)/arch/hi3516cv500/dis.data.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
