MOD_NAME := base
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/base_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/base.o $(DIR)/arch/hi3516cv500/base.data.o
else
    OBJS += $(DIR)/base.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
