MOD_NAME := rc
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/rc_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/rc.o $(DIR)/arch/hi3516cv500/rc.data.o
else
    OBJS += $(DIR)/rc.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
