MOD_NAME := rc
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/rc_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/$(CHIPARCH)/rc$(KO_LOG_SUFFIX).o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
