MOD_NAME := jpege
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/jpege_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/jpege.o $(DIR)/arch/hi3516cv500/jpege.data.o
else
    OBJS += $(DIR)/jpege.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
