MOD_NAME := ao
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/ao_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/ao.o $(DIR)/arch/hi3516cv500/ao.data.o
else
    OBJS += $(DIR)/ao.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
