MOD_NAME := mipi_tx
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/mipi_tx_init.c \
	$(DIR)/mipi_tx.c \
	$(DIR)/mipi_tx_hal.c

ccflags-y += -I$(src)/mipi_tx

OBJS := $(SRCS:%.c=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
