MOD_NAME := vi
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/vi_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/vi.o $(DIR)/arch/hi3516cv500/vi.data.o
else
    OBJS += $(DIR)/vi.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
