MOD_NAME := aenc
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/aenc_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/aenc.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
