MOD_NAME := aenc
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/aenc_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/aenc.o $(DIR)/arch/hi3516cv500/aenc.data.o
else
    OBJS += $(DIR)/aenc.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
