MOD_NAME := acodec
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/acodec_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/acodec.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
