MOD_NAME := acodec
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/acodec_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/acodec.o $(DIR)/arch/hi3516cv500/acodec.data.o
else
    OBJS += $(DIR)/acodec.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
