MOD_NAME := gdc
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/gdc_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/arch/hi3516cv500/gdc.o $(DIR)/arch/hi3516cv500/gdc.data.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
