MOD_NAME := h264e
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/h264e_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/h264e.o

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
