MOD_NAME := h264e
OUT := $(PREFIX)$(MOD_NAME)

DIR=$(MOD_NAME)

SRCS := $(DIR)/h264e_init.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifeq ($(CHIPARCH),hi3516cv500)
    OBJS += $(DIR)/arch/hi3516cv500/h264e.o $(DIR)/arch/hi3516cv500/h264e.data.o
else
    OBJS += $(DIR)/h264e.o
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
