SRCS+=drv/adp/gfbg_drv.c
SRCS+=drv/adp/gfbg_blit.c
SRCS+=drv/adp/gfbg_graphics.c
SRCS+=drv/adp/gfbg_graphics_drv.c
SRCS+=drv/adp/gfbg_graphic_hal.c
SRCS+=drv/adp/gfbg_comm.c
SRCS+=drv/adp/gfbg_rotate.c
SRCS+=drv/adp/gfbg_rotate_tde.c
