/*
 * Copyright (c) XMEDIA. All rights reserved.
 */

#define CONFIG_CHIP_TYPE 0x72050200

#define CONFIG_SYS_SUPPORT 1
#define CONFIG_SYS_SCALE_COEF_SUPPORT 1

#define CONFIG_VI_SUPPORT 1
#define CONFIG_VI_BT656 1
#define CONFIG_VI_MIPI 1
#define CONFIG_ISP_2DOF_DIS_SUPPORT 1
#define CONFIG_VI_LDCV3_SUPPORT 1
#define CONFIG_VI_USERPIC_SUPPORT 1
#define CONFIG_VI_COVEREX_OVERLAYEX_SUPPORT 1
#define CONFIG_VI_LUMA_SUPPORT 1
#define CONFIG_VI_FPN_SUPPORT 1
#define CONFIG_VI_EXTCHN_SUPPORT 1

#if (defined xm72050500) || (defined xm72050510) || (defined xm72050530) || \
    (defined xm72020330) || (defined xm72050230)
#define CONFIG_VI_HLDC_SUPPORT     1
#endif

#define CONFIG_ISP_SUPPORT 1
#define CONFIG_ISP_AF_SUPPORT 1
#define CONFIG_ISP_CR_SUPPORT 1
#define CONFIG_ISP_PREGAMMA_SUPPORT 1
#define CONFIG_ISP_CA_SUPPORT 1


#define CONFIG_VPSS_SUPPORT 1
#define CONFIG_VPSS_3DNR 1
#define CONFIG_VPSS_CHN0_BUF_WRAP 1
#define CONFIG_VPSS_LUMA_STAT_SUPPORT 1
#define CONFIG_VPSS_VGS_LDC_SUPPORT 1
#define CONFIG_VPSS_VGS_ROTATION_SUPPORT 1
#define CONFIG_VPSS_COVER_SUPPORT 1
#define CONFIG_VPSS_MOSAIC_SUPPORT 1
#define CONFIG_VPSS_BUFFER_REUSE_SUPPORT 1

#define CONFIG_VGS_SUPPORT 1
#define CONFIG_VGS_IVE_PRE_SUPPORT 1
#define CONFIG_VGS_LUMA_STAT_SUPPORT 1

#define CONFIG_CHNL_SUPPORT 1

#define CONFIG_VENC_SUPPORT 1
#define CONFIG_H265E_SUPPORT 1
#define CONFIG_H265E_USERDATA_SUPPORT 1
#define CONFIG_H265E_INTRA_REFRESH_SUPPORT 1
#define CONFIG_H264E_SUPPORT 1
#define CONFIG_H264E_SVC_SUPPORT 1
#define CONFIG_H264E_USERDATA_SUPPORT 1
#define CONFIG_H264E_INTRA_REFRESH_SUPPORT 1
#define CONFIG_JPEGE_SUPPORT 1
#define CONFIG_MJPEGE_SUPPORT 1
#define CONFIG_JPEGE_DCF_SUPPORT 1
#define CONFIG_JPEGE_USERDATA_SUPPORT 1
#define CONFIG_VENC_LOWDELAY_SUPPORT 1
#define CONFIG_VENC_FRAMEBUF_RECYCLE_SUPPORT 1
#define CONFIG_VENC_MPF_VGS_SUPPORT 1
#define CONFIG_VENC_VGS_SUPPORT 1
#define CONFIG_VENC_SMARTP_SUPPORT 1
#define CONFIG_VENC_DUALP_SUPPORT 1
#define CONFIG_VENC_RCNREF_SHARE_SUPPORT 1
#define CONFIG_VENC_DEBREATH_SUPPORT 1
#define CONFIG_VENC_SKIPREF_SUPPORT 1
#define CONFIG_VENC_SCENE0_SUPPORT 1
#define CONFIG_VENC_SCENE1_SUPPORT 1
#define CONFIG_VENC_SCENE2_SUPPORT 1
#define CONFIG_RC_AVBR_SUPPORT 1
#define CONFIG_RC_QPMAP_SUPPORT 1
#define CONFIG_RC_QVBR_SUPPORT 1
#define CONFIG_RC_CVBR_SUPPORT 1

#define CONFIG_VDEC_IP ""

#define CONFIG_VO_SUPPORT 1
#define CONFIG_VO_COVER_OSD_SUPPORT 1
#define CONFIG_VO_VGS 1
#define CONFIG_VO_GRAPH 1

#define CONFIG_REGION_SUPPORT 1
#define CONFIG_RGN_DIFFPIXOSD_SUPPORT 1

#define CONFIG_AUDIO_SUPPORT 1
#define CONFIG_ACODEC_SUPPORT 1
#define CONFIG_ACODEC_VERSION "V750"
#define CONFIG_ACODEC_MAX_GAIN 56
#define CONFIG_ACODEC_MIN_GAIN 0
#define CONFIG_ACODEC_GAIN_STEP 3
#define CONFIG_ACODEC_FAST_POWER_SUPPORT 1
#define CONFIG_DOWNVQE_SUPPORT 1
#define CONFIG_TALKVQE_SUPPORT 1
#define CONFIG_RECORDVQE_SUPPORT 1
#define CONFIG_TALKVQEV2_SUPPORT 1
#define CONFIG_AUDIO_STATIC_REGISTER_SUPPORT 1
#define CONFIG_AUDIO_BCD_SUPPORT 1
#define CONFIG_AUDIO_XM72020300_SUPPORT_BCD 1

#define CONFIG_DRV 1
#define CONFIG_EXTDRV 1
#define CONFIG_INTERDRV 1
#define CONFIG_CIPHER 1
#define CONFIG_USER 1
#define CONFIG_MIPI_RX 1
#define CONFIG_WDG 1
#define CONFIG_SYSCFG 1
#define CONFIG_LSADC 1

#define CONFIG_GFBG_SUPPORT 1
#define CONFIG_GFBG_VGS 1

#define CONFIG_SVP_IVE 1
#define CONFIG_SVP_IVE_NORM_GRAD 1
#define CONFIG_SVP_IVE_ST_CANDI_CORNER 1
#define CONFIG_SVP_IVE_CNN_EX 1
#define CONFIG_SVP_IVP 1
#define CONFIG_SVP_MD 1
#define CONFIG_SVP_QR 1

#define CONFIG_TDE_SUPPORT 1

#define CONFIG_PM_SUPPORT 1


