/*
 * Copyright (c) XMEDIA. All rights reserved.
 */
#ifndef __XMEDIA_API_VO_H__
#define __XMEDIA_API_VO_H__

#include "comm_vo.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

XMEDIA_S32 XMEDIA_API_VO_SetPubAttr(VO_DEV VoDev, const VO_PUB_ATTR_S *pstPubAttr);
XMEDIA_S32 XMEDIA_API_VO_GetPubAttr(VO_DEV VoDev, VO_PUB_ATTR_S *pstPubAttr);

XMEDIA_S32 XMEDIA_API_VO_Enable(VO_DEV VoDev);
XMEDIA_S32 XMEDIA_API_VO_Disable(VO_DEV VoDev);

XMEDIA_S32 XMEDIA_API_VO_CloseFd(XMEDIA_VOID);
XMEDIA_S32 XMEDIA_API_VO_SetUserIntfSyncInfo(VO_DEV VoDev, VO_USER_INTFSYNC_INFO_S *pstUserInfo);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerAttr(VO_LAYER VoLayer, const VO_VIDEO_LAYER_ATTR_S *pstLayerAttr);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerAttr(VO_LAYER VoLayer, VO_VIDEO_LAYER_ATTR_S *pstLayerAttr);

XMEDIA_S32 XMEDIA_API_VO_EnableVideoLayer(VO_LAYER VoLayer);
XMEDIA_S32 XMEDIA_API_VO_DisableVideoLayer(VO_LAYER VoLayer);

XMEDIA_S32 XMEDIA_API_VO_BindVideoLayer(VO_LAYER VoLayer, VO_DEV VoDev);
XMEDIA_S32 XMEDIA_API_VO_UnBindVideoLayer(VO_LAYER VoLayer, VO_DEV VoDev);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerPriority(VO_LAYER VoLayer, XMEDIA_U32 u32Priority);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerPriority(VO_LAYER VoLayer, XMEDIA_U32 *pu32Priority);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerCSC(VO_LAYER VoLayer, const VO_CSC_S *pstVideoCSC);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerCSC(VO_LAYER VoLayer, VO_CSC_S *pstVideoCSC);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerPartitionMode(VO_LAYER VoLayer, VO_PART_MODE_E enPartMode);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerPartitionMode(VO_LAYER VoLayer, VO_PART_MODE_E *penPartMode);

XMEDIA_S32 XMEDIA_API_VO_BatchBegin(VO_LAYER VoLayer);
XMEDIA_S32 XMEDIA_API_VO_BatchEnd(VO_LAYER VoLayer);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerBoundary(VO_LAYER VoLayer, const VO_LAYER_BOUNDARY_S *pstLayerBoundary);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerBoundary(VO_LAYER VoLayer, VO_LAYER_BOUNDARY_S *pstLayerBoundary);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerParam(VO_LAYER VoLayer, const VO_LAYER_PARAM_S *pstLayerParam);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerParam(VO_LAYER VoLayer, VO_LAYER_PARAM_S *pstLayerParam);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerDecompress(VO_LAYER VoLayer, XMEDIA_BOOL bSupportDecompress);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerDecompress(VO_LAYER VoLayer, XMEDIA_BOOL *pbSupportDecompress);

XMEDIA_S32 XMEDIA_API_VO_SetVideoLayerCrop(VO_LAYER VoLayer, const CROP_INFO_S *pstCropInfo);
XMEDIA_S32 XMEDIA_API_VO_GetVideoLayerCrop(VO_LAYER VoLayer, CROP_INFO_S *pstCropInfo);

XMEDIA_S32 XMEDIA_API_VO_SetPlayToleration(VO_LAYER VoLayer, XMEDIA_U32 u32Toleration);
XMEDIA_S32 XMEDIA_API_VO_GetPlayToleration(VO_LAYER VoLayer, XMEDIA_U32 *pu32Toleration);

XMEDIA_S32 XMEDIA_API_VO_GetScreenFrame(VO_LAYER VoLayer, VIDEO_FRAME_INFO_S *pstVFrame, XMEDIA_S32 s32MilliSec);
XMEDIA_S32 XMEDIA_API_VO_ReleaseScreenFrame(VO_LAYER VoLayer, const VIDEO_FRAME_INFO_S *pstVFrame);

XMEDIA_S32 XMEDIA_API_VO_SetDisplayBufLen(VO_LAYER VoLayer, XMEDIA_U32 u32BufLen);
XMEDIA_S32 XMEDIA_API_VO_GetDisplayBufLen(VO_LAYER VoLayer, XMEDIA_U32 *pu32BufLen);

XMEDIA_S32 XMEDIA_API_VO_SetChnAttr(VO_LAYER VoLayer, VO_CHN VoChn, const VO_CHN_ATTR_S *pstChnAttr);
XMEDIA_S32 XMEDIA_API_VO_GetChnAttr(VO_LAYER VoLayer, VO_CHN VoChn, VO_CHN_ATTR_S *pstChnAttr);

XMEDIA_S32 XMEDIA_API_VO_EnableChn(VO_LAYER VoLayer, VO_CHN VoChn);
XMEDIA_S32 XMEDIA_API_VO_DisableChn(VO_LAYER VoLayer, VO_CHN VoChn);

XMEDIA_S32 XMEDIA_API_VO_SetChnParam(VO_LAYER VoLayer, VO_CHN VoChn, const VO_CHN_PARAM_S *pstChnParam);
XMEDIA_S32 XMEDIA_API_VO_GetChnParam(VO_LAYER VoLayer, VO_CHN VoChn, VO_CHN_PARAM_S *pstChnParam);

XMEDIA_S32 XMEDIA_API_VO_SetChnDisplayPosition(VO_LAYER VoLayer, VO_CHN VoChn, const POINT_S *pstDispPos);
XMEDIA_S32 XMEDIA_API_VO_GetChnDisplayPosition(VO_LAYER VoLayer, VO_CHN VoChn, POINT_S *pstDispPos);

XMEDIA_S32 XMEDIA_API_VO_SetChnFrameRate(VO_LAYER VoLayer, VO_CHN VoChn, XMEDIA_S32 s32ChnFrmRate);
XMEDIA_S32 XMEDIA_API_VO_GetChnFrameRate(VO_LAYER VoLayer, VO_CHN VoChn, XMEDIA_S32 *ps32ChnFrmRate);

XMEDIA_S32 XMEDIA_API_VO_GetChnFrame(VO_LAYER VoLayer, VO_CHN VoChn, VIDEO_FRAME_INFO_S *pstFrame, XMEDIA_S32 s32MilliSec);
XMEDIA_S32 XMEDIA_API_VO_ReleaseChnFrame(VO_LAYER VoLayer, VO_CHN VoChn, const VIDEO_FRAME_INFO_S *pstFrame);

XMEDIA_S32 XMEDIA_API_VO_PauseChn(VO_LAYER VoLayer, VO_CHN VoChn);
XMEDIA_S32 XMEDIA_API_VO_ResumeChn(VO_LAYER VoLayer, VO_CHN VoChn);
XMEDIA_S32 XMEDIA_API_VO_StepChn(VO_LAYER VoLayer, VO_CHN VoChn);

XMEDIA_S32 XMEDIA_API_VO_RefreshChn(VO_LAYER VoLayer, VO_CHN VoChn);

XMEDIA_S32 XMEDIA_API_VO_ShowChn(VO_LAYER VoLayer, VO_CHN VoChn);
XMEDIA_S32 XMEDIA_API_VO_HideChn(VO_LAYER VoLayer, VO_CHN VoChn);

XMEDIA_S32 XMEDIA_API_VO_SetZoomInWindow(VO_LAYER VoLayer, VO_CHN VoChn, const VO_ZOOM_ATTR_S *pstZoomAttr);
XMEDIA_S32 XMEDIA_API_VO_GetZoomInWindow(VO_LAYER VoLayer, VO_CHN VoChn, VO_ZOOM_ATTR_S *pstZoomAttr);

XMEDIA_S32 XMEDIA_API_VO_GetChnPTS(VO_LAYER VoLayer, VO_CHN VoChn, XMEDIA_U64 *pu64ChnPTS);
XMEDIA_S32 XMEDIA_API_VO_QueryChnStatus(VO_LAYER VoLayer, VO_CHN VoChn, VO_QUERY_STATUS_S *pstStatus);

XMEDIA_S32 XMEDIA_API_VO_SendFrame(VO_LAYER VoLayer, VO_CHN VoChn, VIDEO_FRAME_INFO_S *pstVFrame, XMEDIA_S32 s32MilliSec);

XMEDIA_S32 XMEDIA_API_VO_ClearChnBuf(VO_LAYER VoLayer, VO_CHN VoChn, XMEDIA_BOOL bClrAll);

XMEDIA_S32 XMEDIA_API_VO_SetChnBorder(VO_LAYER VoLayer, VO_CHN VoChn, const VO_BORDER_S *pstBorder);
XMEDIA_S32 XMEDIA_API_VO_GetChnBorder(VO_LAYER VoLayer, VO_CHN VoChn, VO_BORDER_S *pstBorder);

XMEDIA_S32 XMEDIA_API_VO_SetChnBoundary(VO_LAYER VoLayer, VO_CHN VoChn, const VO_CHN_BOUNDARY_S *pstChnBoundary);
XMEDIA_S32 XMEDIA_API_VO_GetChnBoundary(VO_LAYER VoLayer, VO_CHN VoChn, VO_CHN_BOUNDARY_S *pstChnBoundary);

XMEDIA_S32 XMEDIA_API_VO_SetChnRecvThreshold(VO_LAYER VoLayer, VO_CHN VoChn, XMEDIA_U32 u32Threshold);
XMEDIA_S32 XMEDIA_API_VO_GetChnRecvThreshold(VO_LAYER VoLayer, VO_CHN VoChn, XMEDIA_U32 *pu32Threshold);

XMEDIA_S32 XMEDIA_API_VO_SetChnRotation(VO_LAYER VoLayer, VO_CHN VoChn, ROTATION_E enRotation);
XMEDIA_S32 XMEDIA_API_VO_GetChnRotation(VO_LAYER VoLayer, VO_CHN VoChn, ROTATION_E *penRotation);

XMEDIA_S32 XMEDIA_API_VO_GetChnRegionLuma(VO_LAYER VoLayer, VO_CHN VoChn, VO_REGION_INFO_S *pstRegionInfo,XMEDIA_U64 *pu64LumaData, XMEDIA_S32 s32MilliSec);

XMEDIA_S32 XMEDIA_API_VO_SetWBCSource(VO_WBC VoWBC, const VO_WBC_SOURCE_S *pstWBCSource);
XMEDIA_S32 XMEDIA_API_VO_GetWBCSource(VO_WBC VoWBC, VO_WBC_SOURCE_S *pstWBCSources);

XMEDIA_S32 XMEDIA_API_VO_SetWBCAttr(VO_WBC VoWBC, const VO_WBC_ATTR_S *pstWBCAttr);
XMEDIA_S32 XMEDIA_API_VO_GetWBCAttr(VO_WBC VoWBC, VO_WBC_ATTR_S *pstWBCAttr);

XMEDIA_S32 XMEDIA_API_VO_EnableWBC(VO_WBC VoWBC);
XMEDIA_S32 XMEDIA_API_VO_DisableWBC(VO_WBC VoWBC);

XMEDIA_S32 XMEDIA_API_VO_SetWBCMode(VO_WBC VoWBC, VO_WBC_MODE_E enWBCMode);
XMEDIA_S32 XMEDIA_API_VO_GetWBCMode(VO_WBC VoWBC, VO_WBC_MODE_E *penWBCMode);

XMEDIA_S32 XMEDIA_API_VO_SetWBCDepth(VO_WBC VoWBC, XMEDIA_U32 u32Depth);
XMEDIA_S32 XMEDIA_API_VO_GetWBCDepth(VO_WBC VoWBC, XMEDIA_U32 *pu32Depth);

XMEDIA_S32 XMEDIA_API_VO_GetWBCFrame(VO_WBC VoWBC, VIDEO_FRAME_INFO_S *pstVFrame, XMEDIA_S32 s32MilliSec);
XMEDIA_S32 XMEDIA_API_VO_ReleaseWBCFrame(VO_WBC VoWBC, const VIDEO_FRAME_INFO_S *pstVFrame);

XMEDIA_S32 XMEDIA_API_VO_BindGraphicLayer(GRAPHIC_LAYER GraphicLayer, VO_DEV VoDev);
XMEDIA_S32 XMEDIA_API_VO_UnBindGraphicLayer(GRAPHIC_LAYER GraphicLayer, VO_DEV VoDev);

XMEDIA_S32 XMEDIA_API_VO_SetGraphicLayerCSC(GRAPHIC_LAYER GraphicLayer, const VO_CSC_S *pstCSC);
XMEDIA_S32 XMEDIA_API_VO_GetGraphicLayerCSC(GRAPHIC_LAYER GraphicLayer, VO_CSC_S *pstCSC);

XMEDIA_S32 XMEDIA_API_VO_SetDevFrameRate(VO_DEV VoDev, XMEDIA_U32 u32FrameRate);
XMEDIA_S32 XMEDIA_API_VO_GetDevFrameRate(VO_DEV VoDev, XMEDIA_U32 *pu32FrameRate);

XMEDIA_S32 XMEDIA_API_VO_SetModParam(const VO_MOD_PARAM_S *pstModParam);
XMEDIA_S32 XMEDIA_API_VO_GetModParam(VO_MOD_PARAM_S *pstModParam);
XMEDIA_S32 XMEDIA_API_VO_SetVtth(VO_DEV VoDev, XMEDIA_U32 u32Vtth);
XMEDIA_S32 XMEDIA_API_VO_GetVtth(VO_DEV VoDev, XMEDIA_U32 *pu32Vtth);
XMEDIA_S32 XMEDIA_API_VO_SetVtth2(VO_DEV VoDev, XMEDIA_U32 u32Vtth);
XMEDIA_S32 XMEDIA_API_VO_GetVtth2(VO_DEV VoDev, XMEDIA_U32 *pu32Vtth);
XMEDIA_S32 XMEDIA_API_VO_SetChnMirror(VO_LAYER VoLayer, VO_CHN VoChn, VO_MIRROR_MODE_E enMirrorMode);
XMEDIA_S32 XMEDIA_API_VO_GetChnMirror(VO_LAYER VoLayer, VO_CHN VoChn, VO_MIRROR_MODE_E *penMirrorMode);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif


