/*
 * Copyright (c) XMEDIA. All rights reserved.
 */
#ifndef _XMEDIA_API_IVE_H_
#define _XMEDIA_API_IVE_H_

#include "ive.h"

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

XMEDIA_S32 XMEDIA_API_IVE_DMA(IVE_HANDLE *pIveHandle, IVE_DATA_S *pstSrc, IVE_DST_DATA_S *pstDst,IVE_DMA_CTRL_S *pstDmaCtrl, XMEDIA_BOOL bInstant);


XMEDIA_S32 XMEDIA_API_IVE_Filter(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_FILTER_CTRL_S *pstFltCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_CSC(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_CSC_CTRL_S *pstCscCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_FilterAndCSC(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_FILTER_AND_CSC_CTRL_S *pstFltCscCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Sobel(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDstH,IVE_DST_IMAGE_S *pstDstV, IVE_SOBEL_CTRL_S *pstSobelCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_MagAndAng(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDstMag,IVE_DST_IMAGE_S *pstDstAng, IVE_MAG_AND_ANG_CTRL_S *pstMagAndAngCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Dilate(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_DILATE_CTRL_S *pstDilateCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Erode(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_ERODE_CTRL_S *pstErodeCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Thresh(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_THRESH_CTRL_S *pstThrCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_And(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc1, IVE_SRC_IMAGE_S *pstSrc2,IVE_DST_IMAGE_S *pstDst, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Sub(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc1, IVE_SRC_IMAGE_S *pstSrc2,IVE_DST_IMAGE_S *pstDst, IVE_SUB_CTRL_S *pstSubCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Or(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc1, IVE_SRC_IMAGE_S *pstSrc2,IVE_DST_IMAGE_S *pstDst, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Integ(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_INTEG_CTRL_S *pstIntegCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Hist(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_MEM_INFO_S *pstDst,XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Thresh_S16(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_THRESH_S16_CTRL_S *pstThrS16Ctrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Thresh_U16(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_THRESH_U16_CTRL_S *pstThrU16Ctrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_16BitTo8Bit(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_16BIT_TO_8BIT_CTRL_S *pst16BitTo8BitCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_OrdStatFilter(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_ORD_STAT_FILTER_CTRL_S *pstOrdStatFltCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Map(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_SRC_MEM_INFO_S *pstMap,IVE_DST_IMAGE_S *pstDst, IVE_MAP_CTRL_S *pstMapCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_EqualizeHist(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_EQUALIZE_HIST_CTRL_S *pstEqualizeHistCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Add(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc1, IVE_SRC_IMAGE_S *pstSrc2,IVE_DST_IMAGE_S *pstDst, IVE_ADD_CTRL_S *pstAddCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Xor(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc1, IVE_SRC_IMAGE_S *pstSrc2,IVE_DST_IMAGE_S *pstDst, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_NCC(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc1, IVE_SRC_IMAGE_S *pstSrc2,IVE_DST_MEM_INFO_S *pstDst, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_CCL(IVE_HANDLE *pIveHandle, IVE_IMAGE_S *pstSrcDst, IVE_DST_MEM_INFO_S *pstBlob,IVE_CCL_CTRL_S *pstCclCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_GMM(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstFg,IVE_DST_IMAGE_S *pstBg, IVE_MEM_INFO_S *pstModel, IVE_GMM_CTRL_S *pstGmmCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_GMM2(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_SRC_IMAGE_S *pstFactor,IVE_DST_IMAGE_S *pstFg, IVE_DST_IMAGE_S *pstBg, IVE_DST_IMAGE_S *pstMatchModelInfo, IVE_MEM_INFO_S *pstModel,IVE_GMM2_CTRL_S *pstGmm2Ctrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_CannyHysEdge(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstEdge,IVE_DST_MEM_INFO_S *pstStack, IVE_CANNY_HYS_EDGE_CTRL_S *pstCannyHysEdgeCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_CannyEdge(IVE_IMAGE_S *pstEdge, IVE_MEM_INFO_S *pstStack);

XMEDIA_S32 XMEDIA_API_IVE_LBP(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDst,IVE_LBP_CTRL_S *pstLbpCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_NormGrad(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstDstH,IVE_DST_IMAGE_S *pstDstV, IVE_DST_IMAGE_S *pstDstHV, IVE_NORM_GRAD_CTRL_S *pstNormGradCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_LKOpticalFlowPyr(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S astSrcPrevPyr[],IVE_SRC_IMAGE_S astSrcNextPyr[], IVE_SRC_MEM_INFO_S *pstPrevPts, IVE_MEM_INFO_S *pstNextPts,IVE_DST_MEM_INFO_S *pstStatus, IVE_DST_MEM_INFO_S *pstErr, IVE_LK_OPTICAL_FLOW_PYR_CTRL_S *pstLkOptiFlowPyrCtrl,XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_STCandiCorner(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_DST_IMAGE_S *pstCandiCorner,IVE_ST_CANDI_CORNER_CTRL_S *pstStCandiCornerCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_STCorner(IVE_SRC_IMAGE_S *pstCandiCorner, IVE_DST_MEM_INFO_S *pstCorner,IVE_ST_CORNER_CTRL_S *pstStCornerCtrl);

XMEDIA_S32 XMEDIA_API_IVE_GradFg(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstBgDiffFg, IVE_SRC_IMAGE_S *pstCurGrad,IVE_SRC_IMAGE_S *pstBgGrad, IVE_DST_IMAGE_S *pstGradFg, IVE_GRAD_FG_CTRL_S *pstGradFgCtrl, XMEDIA_BOOL bInstant);


XMEDIA_S32 XMEDIA_API_IVE_MatchBgModel(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstCurImg, IVE_DATA_S *pstBgModel,IVE_IMAGE_S *pstFgFlag, IVE_DST_IMAGE_S *pstBgDiffFg, IVE_DST_IMAGE_S *pstFrmDiffFg,IVE_DST_MEM_INFO_S *pstStatData, IVE_MATCH_BG_MODEL_CTRL_S *pstMatchBgModelCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_UpdateBgModel(IVE_HANDLE *pIveHandle, IVE_DATA_S *pstBgModel, IVE_IMAGE_S *pstFgFlag,IVE_DST_IMAGE_S *pstBgImg, IVE_DST_IMAGE_S *pstChgStaImg, IVE_DST_IMAGE_S *pstChgStaFg,IVE_DST_IMAGE_S *pstChgStaLife, IVE_DST_MEM_INFO_S *pstStatData, IVE_UPDATE_BG_MODEL_CTRL_S *pstUpdateBgModelCtrl,XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_ANN_MLP_LoadModel(const XMEDIA_CHAR *pchFileName, IVE_ANN_MLP_MODEL_S *pstAnnMlpModel);

XMEDIA_VOID XMEDIA_API_IVE_ANN_MLP_UnloadModel(IVE_ANN_MLP_MODEL_S *pstAnnMlpModel);

XMEDIA_S32 XMEDIA_API_IVE_ANN_MLP_Predict(IVE_HANDLE *pIveHandle, IVE_SRC_DATA_S *pstSrc,IVE_LOOK_UP_TABLE_S *pstActivFuncTab, IVE_ANN_MLP_MODEL_S *pstAnnMlpModel, IVE_DST_DATA_S *pstDst,XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_SVM_LoadModel(const XMEDIA_CHAR *pchFileName, IVE_SVM_MODEL_S *pstSvmModel);

XMEDIA_VOID XMEDIA_API_IVE_SVM_UnloadModel(IVE_SVM_MODEL_S *pstSvmModel);

XMEDIA_S32 XMEDIA_API_IVE_SVM_Predict(IVE_HANDLE *pIveHandle, IVE_SRC_DATA_S *pstSrc, IVE_LOOK_UP_TABLE_S *pstKernelTab,IVE_SVM_MODEL_S *pstSvmModel, IVE_DST_DATA_S *pstDstVote, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_SAD(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc1, IVE_SRC_IMAGE_S *pstSrc2,IVE_DST_IMAGE_S *pstSad, IVE_DST_IMAGE_S *pstThr, IVE_SAD_CTRL_S *pstSadCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Resize(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S astSrc[], IVE_DST_IMAGE_S astDst[],IVE_RESIZE_CTRL_S *pstResizeCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_CNN_LoadModel(const XMEDIA_CHAR *pchFileName, IVE_CNN_MODEL_S *pstCnnModel);

XMEDIA_VOID XMEDIA_API_IVE_CNN_UnloadModel(IVE_CNN_MODEL_S *pstCnnModel);

XMEDIA_S32 XMEDIA_API_IVE_CNN_Predict(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S astSrc[], IVE_CNN_MODEL_S *pstCnnModel,IVE_DST_DATA_S *pstDst, IVE_CNN_CTRL_S *pstCnnCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_CNN_GetResult(IVE_SRC_DATA_S *pstSrc, IVE_DST_MEM_INFO_S *pstDst,IVE_CNN_MODEL_S *pstCnnModel, IVE_CNN_CTRL_S *pstCnnCtrl);

XMEDIA_S32 XMEDIA_API_IVE_PerspTrans(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_RECT_U32_S astRoi[],IVE_SRC_MEM_INFO_S astPointPair[], IVE_DST_IMAGE_S astDst[], IVE_PERSP_TRANS_CTRL_S *pstPerspTransCtrl,XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_KCF_GetMemSize(XMEDIA_U32 u32MaxObjNum, XMEDIA_U32 *pu32Size);

XMEDIA_S32 XMEDIA_API_IVE_KCF_CreateObjList(IVE_MEM_INFO_S *pstMem, XMEDIA_U32 u32MaxObjNum, IVE_KCF_OBJ_LIST_S *pstObjList);

XMEDIA_S32 XMEDIA_API_IVE_KCF_DestroyObjList(IVE_KCF_OBJ_LIST_S *pstObjList);

XMEDIA_S32 XMEDIA_API_IVE_KCF_CreateGaussPeak(XMEDIA_U3Q5 u3q5Padding, IVE_DST_MEM_INFO_S *pstGaussPeak);

XMEDIA_S32 XMEDIA_API_IVE_KCF_CreateCosWin(IVE_DST_MEM_INFO_S *pstCosWinX, IVE_DST_MEM_INFO_S *pstCosWinY);

XMEDIA_S32 XMEDIA_API_IVE_KCF_GetTrainObj(XMEDIA_U3Q5 u3q5Padding, IVE_ROI_INFO_S astRoiInfo[], XMEDIA_U32 u32ObjNum,IVE_MEM_INFO_S *pstCosWinX, IVE_MEM_INFO_S *pstCosWinY, IVE_MEM_INFO_S *pstGaussPeak,IVE_KCF_OBJ_LIST_S *pstObjList);

XMEDIA_S32 XMEDIA_API_IVE_KCF_Process(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_KCF_OBJ_LIST_S *pstObjList,IVE_KCF_PRO_CTRL_S *pstKcfProCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_KCF_GetObjBbox(IVE_KCF_OBJ_LIST_S *pstObjList, IVE_KCF_BBOX_S astBbox[],XMEDIA_U32 *pu32BboxObjNum, IVE_KCF_BBOX_CTRL_S *pstKcfBboxCtrl);

XMEDIA_S32 XMEDIA_API_IVE_KCF_JudgeObjBboxTrackState(IVE_ROI_INFO_S *pstRoiInfo, IVE_KCF_BBOX_S *pstBbox,XMEDIA_BOOL *pbTrackOk);

XMEDIA_S32 XMEDIA_API_IVE_KCF_ObjUpdate(IVE_KCF_OBJ_LIST_S *pstObjList, IVE_KCF_BBOX_S astBbox[],XMEDIA_U32 u32BboxObjNum);

XMEDIA_S32 XMEDIA_API_IVE_Hog(IVE_HANDLE *pIveHandle, IVE_SRC_IMAGE_S *pstSrc, IVE_RECT_U32_S astRoi[],IVE_DST_BLOB_S astDst[], IVE_HOG_CTRL_S *pstHogCtrl, XMEDIA_BOOL bInstant);

XMEDIA_S32 XMEDIA_API_IVE_Query(IVE_HANDLE IveHandle, XMEDIA_BOOL *pbFinish, XMEDIA_BOOL bBlock);

#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif
#endif
